//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Data2Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Data2Container object using the connection string found in the 'Data2Container' section of the application configuration file.
        /// </summary>
        public Data2Container() : base("name=Data2Container", "Data2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Data2Container object.
        /// </summary>
        public Data2Container(string connectionString) : base(connectionString, "Data2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Data2Container object.
        /// </summary>
        public Data2Container(EntityConnection connection) : base(connection, "Data2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Word> Word
        {
            get
            {
                if ((_Word == null))
                {
                    _Word = base.CreateObjectSet<Word>("Word");
                }
                return _Word;
            }
        }
        private ObjectSet<Word> _Word;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Word EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWord(Word word)
        {
            base.AddObject("Word", word);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Data2", Name="Word")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Word : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Word object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="length">Initial value of the Length property.</param>
        /// <param name="cn">Initial value of the cn property.</param>
        /// <param name="an">Initial value of the an property.</param>
        /// <param name="on">Initial value of the on property.</param>
        /// <param name="pp">Initial value of the pp property.</param>
        /// <param name="dp">Initial value of the dp property.</param>
        /// <param name="qp">Initial value of the qp property.</param>
        /// <param name="tv">Initial value of the tv property.</param>
        /// <param name="iv">Initial value of the iv property.</param>
        /// <param name="cv">Initial value of the cv property.</param>
        /// <param name="nv">Initial value of the nv property.</param>
        /// <param name="wv">Initial value of the wv property.</param>
        /// <param name="dv">Initial value of the dv property.</param>
        /// <param name="adjn">Initial value of the adjn property.</param>
        /// <param name="adjs">Initial value of the adjs property.</param>
        /// <param name="bno">Initial value of the bno property.</param>
        /// <param name="ono">Initial value of the ono property.</param>
        /// <param name="cno">Initial value of the cno property.</param>
        /// <param name="mno">Initial value of the mno property.</param>
        /// <param name="ano">Initial value of the ano property.</param>
        /// <param name="nq">Initial value of the nq property.</param>
        /// <param name="vq">Initial value of the vq property.</param>
        /// <param name="advd">Initial value of the advd property.</param>
        /// <param name="advr">Initial value of the advr property.</param>
        /// <param name="advt">Initial value of the advt property.</param>
        /// <param name="advn">Initial value of the advn property.</param>
        /// <param name="prer">Initial value of the prer property.</param>
        /// <param name="pred">Initial value of the pred property.</param>
        /// <param name="prere">Initial value of the prere property.</param>
        /// <param name="prepu">Initial value of the prepu property.</param>
        /// <param name="prec">Initial value of the prec property.</param>
        /// <param name="pree">Initial value of the pree property.</param>
        /// <param name="conu">Initial value of the conu property.</param>
        /// <param name="conp">Initial value of the conp property.</param>
        /// <param name="pars">Initial value of the pars property.</param>
        /// <param name="part">Initial value of the part property.</param>
        /// <param name="parm">Initial value of the parm property.</param>
        /// <param name="inth">Initial value of the inth property.</param>
        /// <param name="ints">Initial value of the ints property.</param>
        /// <param name="inta">Initial value of the inta property.</param>
        /// <param name="intsu">Initial value of the intsu property.</param>
        /// <param name="intc">Initial value of the intc property.</param>
        /// <param name="intr">Initial value of the intr property.</param>
        /// <param name="oo">Initial value of the oo property.</param>
        /// <param name="favor">Initial value of the favor property.</param>
        /// <param name="happy">Initial value of the happy property.</param>
        /// <param name="anger">Initial value of the anger property.</param>
        /// <param name="regex">Initial value of the Regex property.</param>
        /// <param name="zhuWei">Initial value of the ZhuWei property.</param>
        /// <param name="dongBin">Initial value of the DongBin property.</param>
        /// <param name="pianZhengDingZhong">Initial value of the PianZhengDingZhong property.</param>
        /// <param name="pianZhengZhuangZhong">Initial value of the PianZhengZhuangZhong property.</param>
        /// <param name="zhongBu">Initial value of the ZhongBu property.</param>
        /// <param name="lianHe">Initial value of the LianHe property.</param>
        /// <param name="lianWei">Initial value of the LianWei property.</param>
        /// <param name="jianYu">Initial value of the JianYu property.</param>
        /// <param name="tongWei">Initial value of the TongWei property.</param>
        /// <param name="fangWei">Initial value of the FangWei property.</param>
        public static Word CreateWord(global::System.Int64 id, global::System.String content, global::System.Int32 length, global::System.Boolean cn, global::System.Boolean an, global::System.Boolean on, global::System.Boolean pp, global::System.Boolean dp, global::System.Boolean qp, global::System.Boolean tv, global::System.Boolean iv, global::System.Boolean cv, global::System.Boolean nv, global::System.Boolean wv, global::System.Boolean dv, global::System.Boolean adjn, global::System.Boolean adjs, global::System.Boolean bno, global::System.Boolean ono, global::System.Boolean cno, global::System.Boolean mno, global::System.Boolean ano, global::System.Boolean nq, global::System.Boolean vq, global::System.Boolean advd, global::System.Boolean advr, global::System.Boolean advt, global::System.Boolean advn, global::System.Boolean prer, global::System.Boolean pred, global::System.Boolean prere, global::System.Boolean prepu, global::System.Boolean prec, global::System.Boolean pree, global::System.Boolean conu, global::System.Boolean conp, global::System.Boolean pars, global::System.Boolean part, global::System.Boolean parm, global::System.Boolean inth, global::System.Boolean ints, global::System.Boolean inta, global::System.Boolean intsu, global::System.Boolean intc, global::System.Boolean intr, global::System.Boolean oo, global::System.Int32 favor, global::System.Int32 happy, global::System.Int32 anger, global::System.String regex, global::System.Boolean zhuWei, global::System.Boolean dongBin, global::System.Boolean pianZhengDingZhong, global::System.Boolean pianZhengZhuangZhong, global::System.Boolean zhongBu, global::System.Boolean lianHe, global::System.Boolean lianWei, global::System.Boolean jianYu, global::System.Boolean tongWei, global::System.Boolean fangWei)
        {
            Word word = new Word();
            word.Id = id;
            word.Content = content;
            word.Length = length;
            word.cn = cn;
            word.an = an;
            word.on = on;
            word.pp = pp;
            word.dp = dp;
            word.qp = qp;
            word.tv = tv;
            word.iv = iv;
            word.cv = cv;
            word.nv = nv;
            word.wv = wv;
            word.dv = dv;
            word.adjn = adjn;
            word.adjs = adjs;
            word.bno = bno;
            word.ono = ono;
            word.cno = cno;
            word.mno = mno;
            word.ano = ano;
            word.nq = nq;
            word.vq = vq;
            word.advd = advd;
            word.advr = advr;
            word.advt = advt;
            word.advn = advn;
            word.prer = prer;
            word.pred = pred;
            word.prere = prere;
            word.prepu = prepu;
            word.prec = prec;
            word.pree = pree;
            word.conu = conu;
            word.conp = conp;
            word.pars = pars;
            word.part = part;
            word.parm = parm;
            word.inth = inth;
            word.ints = ints;
            word.inta = inta;
            word.intsu = intsu;
            word.intc = intc;
            word.intr = intr;
            word.oo = oo;
            word.favor = favor;
            word.happy = happy;
            word.anger = anger;
            word.Regex = regex;
            word.ZhuWei = zhuWei;
            word.DongBin = dongBin;
            word.PianZhengDingZhong = pianZhengDingZhong;
            word.PianZhengZhuangZhong = pianZhengZhuangZhong;
            word.ZhongBu = zhongBu;
            word.LianHe = lianHe;
            word.LianWei = lianWei;
            word.JianYu = jianYu;
            word.TongWei = tongWei;
            word.FangWei = fangWei;
            return word;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private global::System.Int32 _Length;
        partial void OnLengthChanging(global::System.Int32 value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// 具体名词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cn
        {
            get
            {
                return _cn;
            }
            set
            {
                OncnChanging(value);
                ReportPropertyChanging("cn");
                _cn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cn");
                OncnChanged();
            }
        }
        private global::System.Boolean _cn;
        partial void OncnChanging(global::System.Boolean value);
        partial void OncnChanged();
    
        /// <summary>
        /// 抽象名词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean an
        {
            get
            {
                return _an;
            }
            set
            {
                OnanChanging(value);
                ReportPropertyChanging("an");
                _an = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("an");
                OnanChanged();
            }
        }
        private global::System.Boolean _an;
        partial void OnanChanging(global::System.Boolean value);
        partial void OnanChanged();
    
        /// <summary>
        /// 方位名词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean on
        {
            get
            {
                return _on;
            }
            set
            {
                OnonChanging(value);
                ReportPropertyChanging("on");
                _on = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("on");
                OnonChanged();
            }
        }
        private global::System.Boolean _on;
        partial void OnonChanging(global::System.Boolean value);
        partial void OnonChanged();
    
        /// <summary>
        /// 人称代词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean pp
        {
            get
            {
                return _pp;
            }
            set
            {
                OnppChanging(value);
                ReportPropertyChanging("pp");
                _pp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pp");
                OnppChanged();
            }
        }
        private global::System.Boolean _pp;
        partial void OnppChanging(global::System.Boolean value);
        partial void OnppChanged();
    
        /// <summary>
        /// 指示代词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean dp
        {
            get
            {
                return _dp;
            }
            set
            {
                OndpChanging(value);
                ReportPropertyChanging("dp");
                _dp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dp");
                OndpChanged();
            }
        }
        private global::System.Boolean _dp;
        partial void OndpChanging(global::System.Boolean value);
        partial void OndpChanged();
    
        /// <summary>
        /// 疑问代词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean qp
        {
            get
            {
                return _qp;
            }
            set
            {
                OnqpChanging(value);
                ReportPropertyChanging("qp");
                _qp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qp");
                OnqpChanged();
            }
        }
        private global::System.Boolean _qp;
        partial void OnqpChanging(global::System.Boolean value);
        partial void OnqpChanged();
    
        /// <summary>
        /// 及物动词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean tv
        {
            get
            {
                return _tv;
            }
            set
            {
                OntvChanging(value);
                ReportPropertyChanging("tv");
                _tv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tv");
                OntvChanged();
            }
        }
        private global::System.Boolean _tv;
        partial void OntvChanging(global::System.Boolean value);
        partial void OntvChanged();
    
        /// <summary>
        /// 不及物动词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean iv
        {
            get
            {
                return _iv;
            }
            set
            {
                OnivChanging(value);
                ReportPropertyChanging("iv");
                _iv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iv");
                OnivChanged();
            }
        }
        private global::System.Boolean _iv;
        partial void OnivChanging(global::System.Boolean value);
        partial void OnivChanged();
    
        /// <summary>
        /// 能源动词 可能
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cv
        {
            get
            {
                return _cv;
            }
            set
            {
                OncvChanging(value);
                ReportPropertyChanging("cv");
                _cv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cv");
                OncvChanged();
            }
        }
        private global::System.Boolean _cv;
        partial void OncvChanging(global::System.Boolean value);
        partial void OncvChanged();
    
        /// <summary>
        /// 能愿动词 必要
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean nv
        {
            get
            {
                return _nv;
            }
            set
            {
                OnnvChanging(value);
                ReportPropertyChanging("nv");
                _nv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nv");
                OnnvChanged();
            }
        }
        private global::System.Boolean _nv;
        partial void OnnvChanging(global::System.Boolean value);
        partial void OnnvChanged();
    
        /// <summary>
        /// 能愿动词 愿意
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean wv
        {
            get
            {
                return _wv;
            }
            set
            {
                OnwvChanging(value);
                ReportPropertyChanging("wv");
                _wv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wv");
                OnwvChanged();
            }
        }
        private global::System.Boolean _wv;
        partial void OnwvChanging(global::System.Boolean value);
        partial void OnwvChanged();
    
        /// <summary>
        /// 趋向动词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean dv
        {
            get
            {
                return _dv;
            }
            set
            {
                OndvChanging(value);
                ReportPropertyChanging("dv");
                _dv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dv");
                OndvChanged();
            }
        }
        private global::System.Boolean _dv;
        partial void OndvChanging(global::System.Boolean value);
        partial void OndvChanged();
    
        /// <summary>
        /// 形容词 性质
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean adjn
        {
            get
            {
                return _adjn;
            }
            set
            {
                OnadjnChanging(value);
                ReportPropertyChanging("adjn");
                _adjn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjn");
                OnadjnChanged();
            }
        }
        private global::System.Boolean _adjn;
        partial void OnadjnChanging(global::System.Boolean value);
        partial void OnadjnChanged();
    
        /// <summary>
        /// 形容词-状态
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean adjs
        {
            get
            {
                return _adjs;
            }
            set
            {
                OnadjsChanging(value);
                ReportPropertyChanging("adjs");
                _adjs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjs");
                OnadjsChanged();
            }
        }
        private global::System.Boolean _adjs;
        partial void OnadjsChanging(global::System.Boolean value);
        partial void OnadjsChanged();
    
        /// <summary>
        /// 基数
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean bno
        {
            get
            {
                return _bno;
            }
            set
            {
                OnbnoChanging(value);
                ReportPropertyChanging("bno");
                _bno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bno");
                OnbnoChanged();
            }
        }
        private global::System.Boolean _bno;
        partial void OnbnoChanging(global::System.Boolean value);
        partial void OnbnoChanged();
    
        /// <summary>
        /// 序数
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ono
        {
            get
            {
                return _ono;
            }
            set
            {
                OnonoChanging(value);
                ReportPropertyChanging("ono");
                _ono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ono");
                OnonoChanged();
            }
        }
        private global::System.Boolean _ono;
        partial void OnonoChanging(global::System.Boolean value);
        partial void OnonoChanged();
    
        /// <summary>
        /// 分数
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cno
        {
            get
            {
                return _cno;
            }
            set
            {
                OncnoChanging(value);
                ReportPropertyChanging("cno");
                _cno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cno");
                OncnoChanged();
            }
        }
        private global::System.Boolean _cno;
        partial void OncnoChanging(global::System.Boolean value);
        partial void OncnoChanged();
    
        /// <summary>
        /// 倍数
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean mno
        {
            get
            {
                return _mno;
            }
            set
            {
                OnmnoChanging(value);
                ReportPropertyChanging("mno");
                _mno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mno");
                OnmnoChanged();
            }
        }
        private global::System.Boolean _mno;
        partial void OnmnoChanging(global::System.Boolean value);
        partial void OnmnoChanged();
    
        /// <summary>
        /// 概数
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ano
        {
            get
            {
                return _ano;
            }
            set
            {
                OnanoChanging(value);
                ReportPropertyChanging("ano");
                _ano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ano");
                OnanoChanged();
            }
        }
        private global::System.Boolean _ano;
        partial void OnanoChanging(global::System.Boolean value);
        partial void OnanoChanged();
    
        /// <summary>
        /// 名量词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean nq
        {
            get
            {
                return _nq;
            }
            set
            {
                OnnqChanging(value);
                ReportPropertyChanging("nq");
                _nq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nq");
                OnnqChanged();
            }
        }
        private global::System.Boolean _nq;
        partial void OnnqChanging(global::System.Boolean value);
        partial void OnnqChanged();
    
        /// <summary>
        /// 动量词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean vq
        {
            get
            {
                return _vq;
            }
            set
            {
                OnvqChanging(value);
                ReportPropertyChanging("vq");
                _vq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vq");
                OnvqChanged();
            }
        }
        private global::System.Boolean _vq;
        partial void OnvqChanging(global::System.Boolean value);
        partial void OnvqChanged();
    
        /// <summary>
        /// 副词程度
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean advd
        {
            get
            {
                return _advd;
            }
            set
            {
                OnadvdChanging(value);
                ReportPropertyChanging("advd");
                _advd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("advd");
                OnadvdChanged();
            }
        }
        private global::System.Boolean _advd;
        partial void OnadvdChanging(global::System.Boolean value);
        partial void OnadvdChanged();
    
        /// <summary>
        /// 副词范围
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean advr
        {
            get
            {
                return _advr;
            }
            set
            {
                OnadvrChanging(value);
                ReportPropertyChanging("advr");
                _advr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("advr");
                OnadvrChanged();
            }
        }
        private global::System.Boolean _advr;
        partial void OnadvrChanging(global::System.Boolean value);
        partial void OnadvrChanged();
    
        /// <summary>
        /// 副词时间
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean advt
        {
            get
            {
                return _advt;
            }
            set
            {
                OnadvtChanging(value);
                ReportPropertyChanging("advt");
                _advt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("advt");
                OnadvtChanged();
            }
        }
        private global::System.Boolean _advt;
        partial void OnadvtChanging(global::System.Boolean value);
        partial void OnadvtChanged();
    
        /// <summary>
        /// 副词否定
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean advn
        {
            get
            {
                return _advn;
            }
            set
            {
                OnadvnChanging(value);
                ReportPropertyChanging("advn");
                _advn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("advn");
                OnadvnChanged();
            }
        }
        private global::System.Boolean _advn;
        partial void OnadvnChanging(global::System.Boolean value);
        partial void OnadvnChanged();
    
        /// <summary>
        /// 介词对象关系
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean prer
        {
            get
            {
                return _prer;
            }
            set
            {
                OnprerChanging(value);
                ReportPropertyChanging("prer");
                _prer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prer");
                OnprerChanged();
            }
        }
        private global::System.Boolean _prer;
        partial void OnprerChanging(global::System.Boolean value);
        partial void OnprerChanged();
    
        /// <summary>
        /// 介词住所方位
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean pred
        {
            get
            {
                return _pred;
            }
            set
            {
                OnpredChanging(value);
                ReportPropertyChanging("pred");
                _pred = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pred");
                OnpredChanged();
            }
        }
        private global::System.Boolean _pred;
        partial void OnpredChanging(global::System.Boolean value);
        partial void OnpredChanged();
    
        /// <summary>
        /// 介词 原因
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean prere
        {
            get
            {
                return _prere;
            }
            set
            {
                OnprereChanging(value);
                ReportPropertyChanging("prere");
                _prere = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prere");
                OnprereChanged();
            }
        }
        private global::System.Boolean _prere;
        partial void OnprereChanging(global::System.Boolean value);
        partial void OnprereChanged();
    
        /// <summary>
        /// 介词目的
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean prepu
        {
            get
            {
                return _prepu;
            }
            set
            {
                OnprepuChanging(value);
                ReportPropertyChanging("prepu");
                _prepu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prepu");
                OnprepuChanged();
            }
        }
        private global::System.Boolean _prepu;
        partial void OnprepuChanging(global::System.Boolean value);
        partial void OnprepuChanged();
    
        /// <summary>
        /// 介词比较
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean prec
        {
            get
            {
                return _prec;
            }
            set
            {
                OnprecChanging(value);
                ReportPropertyChanging("prec");
                _prec = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prec");
                OnprecChanged();
            }
        }
        private global::System.Boolean _prec;
        partial void OnprecChanging(global::System.Boolean value);
        partial void OnprecChanged();
    
        /// <summary>
        /// 介词排除
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean pree
        {
            get
            {
                return _pree;
            }
            set
            {
                OnpreeChanging(value);
                ReportPropertyChanging("pree");
                _pree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pree");
                OnpreeChanged();
            }
        }
        private global::System.Boolean _pree;
        partial void OnpreeChanging(global::System.Boolean value);
        partial void OnpreeChanged();
    
        /// <summary>
        /// 连词联合
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean conu
        {
            get
            {
                return _conu;
            }
            set
            {
                OnconuChanging(value);
                ReportPropertyChanging("conu");
                _conu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("conu");
                OnconuChanged();
            }
        }
        private global::System.Boolean _conu;
        partial void OnconuChanging(global::System.Boolean value);
        partial void OnconuChanged();
    
        /// <summary>
        /// 连词偏正
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean conp
        {
            get
            {
                return _conp;
            }
            set
            {
                OnconpChanging(value);
                ReportPropertyChanging("conp");
                _conp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("conp");
                OnconpChanged();
            }
        }
        private global::System.Boolean _conp;
        partial void OnconpChanging(global::System.Boolean value);
        partial void OnconpChanged();
    
        /// <summary>
        /// 助词结构
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean pars
        {
            get
            {
                return _pars;
            }
            set
            {
                OnparsChanging(value);
                ReportPropertyChanging("pars");
                _pars = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pars");
                OnparsChanged();
            }
        }
        private global::System.Boolean _pars;
        partial void OnparsChanging(global::System.Boolean value);
        partial void OnparsChanged();
    
        /// <summary>
        /// 助词时态
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean part
        {
            get
            {
                return _part;
            }
            set
            {
                OnpartChanging(value);
                ReportPropertyChanging("part");
                _part = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("part");
                OnpartChanged();
            }
        }
        private global::System.Boolean _part;
        partial void OnpartChanging(global::System.Boolean value);
        partial void OnpartChanged();
    
        /// <summary>
        /// 助词语气
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean parm
        {
            get
            {
                return _parm;
            }
            set
            {
                OnparmChanging(value);
                ReportPropertyChanging("parm");
                _parm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parm");
                OnparmChanged();
            }
        }
        private global::System.Boolean _parm;
        partial void OnparmChanging(global::System.Boolean value);
        partial void OnparmChanged();
    
        /// <summary>
        /// 叹词喜悦
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean inth
        {
            get
            {
                return _inth;
            }
            set
            {
                OninthChanging(value);
                ReportPropertyChanging("inth");
                _inth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inth");
                OninthChanged();
            }
        }
        private global::System.Boolean _inth;
        partial void OninthChanging(global::System.Boolean value);
        partial void OninthChanged();
    
        /// <summary>
        /// 叹词悲伤
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ints
        {
            get
            {
                return _ints;
            }
            set
            {
                OnintsChanging(value);
                ReportPropertyChanging("ints");
                _ints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ints");
                OnintsChanged();
            }
        }
        private global::System.Boolean _ints;
        partial void OnintsChanging(global::System.Boolean value);
        partial void OnintsChanged();
    
        /// <summary>
        /// 叹词愤怒
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean inta
        {
            get
            {
                return _inta;
            }
            set
            {
                OnintaChanging(value);
                ReportPropertyChanging("inta");
                _inta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inta");
                OnintaChanged();
            }
        }
        private global::System.Boolean _inta;
        partial void OnintaChanging(global::System.Boolean value);
        partial void OnintaChanged();
    
        /// <summary>
        /// 叹词惊讶
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean intsu
        {
            get
            {
                return _intsu;
            }
            set
            {
                OnintsuChanging(value);
                ReportPropertyChanging("intsu");
                _intsu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("intsu");
                OnintsuChanged();
            }
        }
        private global::System.Boolean _intsu;
        partial void OnintsuChanging(global::System.Boolean value);
        partial void OnintsuChanged();
    
        /// <summary>
        /// 叹词呼唤
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean intc
        {
            get
            {
                return _intc;
            }
            set
            {
                OnintcChanging(value);
                ReportPropertyChanging("intc");
                _intc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("intc");
                OnintcChanged();
            }
        }
        private global::System.Boolean _intc;
        partial void OnintcChanging(global::System.Boolean value);
        partial void OnintcChanged();
    
        /// <summary>
        /// 叹词应答
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean intr
        {
            get
            {
                return _intr;
            }
            set
            {
                OnintrChanging(value);
                ReportPropertyChanging("intr");
                _intr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("intr");
                OnintrChanged();
            }
        }
        private global::System.Boolean _intr;
        partial void OnintrChanging(global::System.Boolean value);
        partial void OnintrChanged();
    
        /// <summary>
        /// 叹词
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean oo
        {
            get
            {
                return _oo;
            }
            set
            {
                OnooChanging(value);
                ReportPropertyChanging("oo");
                _oo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oo");
                OnooChanged();
            }
        }
        private global::System.Boolean _oo;
        partial void OnooChanging(global::System.Boolean value);
        partial void OnooChanged();
    
        /// <summary>
        /// 喜欢程度
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 favor
        {
            get
            {
                return _favor;
            }
            set
            {
                OnfavorChanging(value);
                ReportPropertyChanging("favor");
                _favor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("favor");
                OnfavorChanged();
            }
        }
        private global::System.Int32 _favor;
        partial void OnfavorChanging(global::System.Int32 value);
        partial void OnfavorChanged();
    
        /// <summary>
        /// 欢乐程度
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 happy
        {
            get
            {
                return _happy;
            }
            set
            {
                OnhappyChanging(value);
                ReportPropertyChanging("happy");
                _happy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("happy");
                OnhappyChanged();
            }
        }
        private global::System.Int32 _happy;
        partial void OnhappyChanging(global::System.Int32 value);
        partial void OnhappyChanged();
    
        /// <summary>
        /// 愤怒程度
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 anger
        {
            get
            {
                return _anger;
            }
            set
            {
                OnangerChanging(value);
                ReportPropertyChanging("anger");
                _anger = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anger");
                OnangerChanged();
            }
        }
        private global::System.Int32 _anger;
        partial void OnangerChanging(global::System.Int32 value);
        partial void OnangerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Regex
        {
            get
            {
                return _Regex;
            }
            set
            {
                OnRegexChanging(value);
                ReportPropertyChanging("Regex");
                _Regex = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Regex");
                OnRegexChanged();
            }
        }
        private global::System.String _Regex;
        partial void OnRegexChanging(global::System.String value);
        partial void OnRegexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ZhuWei
        {
            get
            {
                return _ZhuWei;
            }
            set
            {
                OnZhuWeiChanging(value);
                ReportPropertyChanging("ZhuWei");
                _ZhuWei = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZhuWei");
                OnZhuWeiChanged();
            }
        }
        private global::System.Boolean _ZhuWei;
        partial void OnZhuWeiChanging(global::System.Boolean value);
        partial void OnZhuWeiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DongBin
        {
            get
            {
                return _DongBin;
            }
            set
            {
                OnDongBinChanging(value);
                ReportPropertyChanging("DongBin");
                _DongBin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DongBin");
                OnDongBinChanged();
            }
        }
        private global::System.Boolean _DongBin;
        partial void OnDongBinChanging(global::System.Boolean value);
        partial void OnDongBinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PianZhengDingZhong
        {
            get
            {
                return _PianZhengDingZhong;
            }
            set
            {
                OnPianZhengDingZhongChanging(value);
                ReportPropertyChanging("PianZhengDingZhong");
                _PianZhengDingZhong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PianZhengDingZhong");
                OnPianZhengDingZhongChanged();
            }
        }
        private global::System.Boolean _PianZhengDingZhong;
        partial void OnPianZhengDingZhongChanging(global::System.Boolean value);
        partial void OnPianZhengDingZhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PianZhengZhuangZhong
        {
            get
            {
                return _PianZhengZhuangZhong;
            }
            set
            {
                OnPianZhengZhuangZhongChanging(value);
                ReportPropertyChanging("PianZhengZhuangZhong");
                _PianZhengZhuangZhong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PianZhengZhuangZhong");
                OnPianZhengZhuangZhongChanged();
            }
        }
        private global::System.Boolean _PianZhengZhuangZhong;
        partial void OnPianZhengZhuangZhongChanging(global::System.Boolean value);
        partial void OnPianZhengZhuangZhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ZhongBu
        {
            get
            {
                return _ZhongBu;
            }
            set
            {
                OnZhongBuChanging(value);
                ReportPropertyChanging("ZhongBu");
                _ZhongBu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZhongBu");
                OnZhongBuChanged();
            }
        }
        private global::System.Boolean _ZhongBu;
        partial void OnZhongBuChanging(global::System.Boolean value);
        partial void OnZhongBuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LianHe
        {
            get
            {
                return _LianHe;
            }
            set
            {
                OnLianHeChanging(value);
                ReportPropertyChanging("LianHe");
                _LianHe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LianHe");
                OnLianHeChanged();
            }
        }
        private global::System.Boolean _LianHe;
        partial void OnLianHeChanging(global::System.Boolean value);
        partial void OnLianHeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LianWei
        {
            get
            {
                return _LianWei;
            }
            set
            {
                OnLianWeiChanging(value);
                ReportPropertyChanging("LianWei");
                _LianWei = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LianWei");
                OnLianWeiChanged();
            }
        }
        private global::System.Boolean _LianWei;
        partial void OnLianWeiChanging(global::System.Boolean value);
        partial void OnLianWeiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean JianYu
        {
            get
            {
                return _JianYu;
            }
            set
            {
                OnJianYuChanging(value);
                ReportPropertyChanging("JianYu");
                _JianYu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JianYu");
                OnJianYuChanged();
            }
        }
        private global::System.Boolean _JianYu;
        partial void OnJianYuChanging(global::System.Boolean value);
        partial void OnJianYuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TongWei
        {
            get
            {
                return _TongWei;
            }
            set
            {
                OnTongWeiChanging(value);
                ReportPropertyChanging("TongWei");
                _TongWei = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TongWei");
                OnTongWeiChanged();
            }
        }
        private global::System.Boolean _TongWei;
        partial void OnTongWeiChanging(global::System.Boolean value);
        partial void OnTongWeiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FangWei
        {
            get
            {
                return _FangWei;
            }
            set
            {
                OnFangWeiChanging(value);
                ReportPropertyChanging("FangWei");
                _FangWei = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FangWei");
                OnFangWeiChanged();
            }
        }
        private global::System.Boolean _FangWei;
        partial void OnFangWeiChanging(global::System.Boolean value);
        partial void OnFangWeiChanged();

        #endregion

    
    }

    #endregion

    
}
